window.gurgleData = {
    resultFaviconPaths: [
        "img/favicons/67.gif",
        "img/favicons/ayo.gif",
        "img/favicons/catwave.gif",
        "img/favicons/excited.gif",
        "img/favicons/lala.gif",
        "img/favicons/mcqueen.gif",
        "img/favicons/money.gif",
        "img/favicons/pikachu.gif",
        "img/favicons/sonic.gif",
        "img/favicons/sparkles.gif",
        "img/favicons/warn.gif",
    ],
    overviewIconPaths: [
        "img/overview/joe.png",
        "img/overview/happybob.gif",
    ],
    introStabs: [
        "Listen, this thing opens like a Reddit self-post",
        "Imagine a midnight meme thread trying to sound academic",
        "Picture a corny caption from your worst Instagram follow",
        "Pretend the answer is getting written in real time by troll engineers",
    ],
    midWeaves: [
        "where analogies spill from dark humor into faux data",
        "while emojis from private subreddits try their best to sound wise",
        "and the tone keeps flipping from serious to 'lol wtf' in one breath",
        "as it layers pseudo logic over a joke template stolen from Reddit Pets",
    ],
    punchlines: [
        "It's nonsense that reads like a brilliant savage commentary.",
        "So you get annoyed, but you also laugh because it sounds smart.",
        "It tries to be helpful while sounding like someone leaking memes.",
        "Consider it the sorta-violent cousin of normal answers.",
    ],
    questionPools: {
        what: [
            "This answer starts by self-affirming that it knows what you're asking",
            "The tone pretends it already understands what you meant",
            "It begins with a confident 'what happens is...' vibe",
        ],
        why: [
            "This sidesteps the reason with a wink, like a Reddit thread quoting shadow facts",
            "It says 'here is why' with enough smugness to sound like dark Instagram humor",
            "It makes a bold claim about cause, then slides into a meme reference",
        ],
        where: [
            "It spits out coordinates that make no sense but sound Instagram-predictive",
            "It frames the place as if a Reddit troll curated it while drunk",
            "It references locations in the tone of a conspiracy subreddit",
        ],
        how: [
            "It offers a pseudo-instructional roadmap straight from a meme crash course",
            "It mixes vague steps with lurid captions you'd find on dark Instagram stories",
            "It pretends to explain 'how' while basically riffing on nonsense",
        ],
        when: [
            "It timestamps the answer like a viral reddit repost with extra flair",
            "It guesstimates timing while referencing late-night Instagram comments",
            "It uses a timeline that feels half fiction, half dark humor",
        ],
        default: [
            "This overview asserts it knows what you're asking",
            "It responds with a juicy-sounding hook",
        ],
    },
    questionSpecial: [
        { pattern: /am i cute/i, theme: "looks" },
        { pattern: /am i hot/i, theme: "attraction" },
        { pattern: /am i smart/i, theme: "brains" },
        { pattern: /will i get a gf/i, theme: "love" },
        { pattern: /do they like me/i, theme: "approval" },
        { pattern: /am i funny/i, theme: "wit" },
    ],
    unhingedImagePool: [
        {
            title: "skibidi speakerwoman reaction gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/Hy0gGmlX5MyD5rU9Uk",
            src: "https://media.giphy.com/media/Hy0gGmlX5MyD5rU9Uk/giphy.gif",
        },
        {
            title: "instagram worst comment gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/meme-instagram-naaayj-QbT876rFX2XJe71qDu",
            src: "https://media.giphy.com/media/QbT876rFX2XJe71qDu/giphy.gif",
        },
        {
            title: "cat toilet skibidi bell gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/kittens-ding-dong-bell-it-aint-skibidi-PTmDYbYT6yHyKBThwp",
            src: "https://media.giphy.com/media/PTmDYbYT6yHyKBThwp/giphy.gif",
        },
        {
            title: "gamer wtf ohio toilet gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/toilet-skibidi-skibiditoilet-qv1MlmBCqhJzVegKsL",
            src: "https://media.giphy.com/media/qv1MlmBCqhJzVegKsL/giphy.gif",
        },
        {
            title: "sigma genz skibidi gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/memes-skibiditoilet-domdomyesyes-ZJ8gpVz8QOdoj4RETH",
            src: "https://media.giphy.com/media/ZJ8gpVz8QOdoj4RETH/giphy.gif",
        },
        {
            title: "ohio high five sports gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/ohiostathletics-1luULdkNZkzgVULYRa",
            src: "https://media.giphy.com/media/1luULdkNZkzgVULYRa/giphy.gif",
        },
        {
            title: "skibidi titan telescope gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/skibidi-toilet-titan-telescope-qg8faAh2PF0NS7VORT",
            src: "https://media.giphy.com/media/qg8faAh2PF0NS7VORT/giphy.gif",
        },
        {
            title: "skibidi rizz podcast gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/PopCultureWeekly-skibidi-toilet-rizz-TWuib3xkZ7gun7URFu",
            src: "https://media.giphy.com/media/TWuib3xkZ7gun7URFu/giphy.gif",
        },
        {
            title: "instagram meme hallway walk gif",
            service: "Tenor",
            href: "https://tenor.com/view/instagram-memes-meme-pages-prank-gif-10490781",
            src: "https://media1.tenor.com/m/8mzEpdVRrZoAAAAd/instagram-memes.gif",
        },
        {
            title: "instagram logo glitch gif",
            service: "Tenor",
            href: "https://tenor.com/view/instagram-gif-4599774131825471660",
            src: "https://media.tenor.com/abIMTwN_d4UAAAAM/glitch-insta.gif",
        },
        {
            title: "instagram follow me gif",
            service: "Tenor",
            href: "https://tenor.com/view/instagram-gif-4599774131825471660",
            src: "https://media.tenor.com/Q4yv4dJaD68AAAAM/glich-instagram.gif",
        },
        {
            title: "instagram logo splash gif",
            service: "Tenor",
            href: "https://tenor.com/view/instagram-memes-meme-pages-prank-gif-10490781",
            src: "https://media.tenor.com/VT6FD07iaBgAAAAM/instagram-mycrxn.gif",
        },
        {
            title: "all in his mind c4 corvette gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/c4-corvette-I3jrzQVninjDfQFUe2",
            src: "https://media.giphy.com/media/I3jrzQVninjDfQFUe2/giphy.gif",
        },
        {
            title: "will it work blueprint gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/kodd-shoot-001-01-p7311wYxKrBcXL2s2X",
            src: "https://media.giphy.com/media/p7311wYxKrBcXL2s2X/giphy.gif",
        },
        {
            title: "will it work satire gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/satire-will-it-work-meme-87Gx1ArW4WVQahvJpC",
            src: "https://media.giphy.com/media/87Gx1ArW4WVQahvJpC/giphy.gif",
        },
        {
            title: "will it work airball gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/IAysdLOmRe2V865dLA",
            src: "https://media.giphy.com/media/IAysdLOmRe2V865dLA/giphy.gif",
        },
        {
            title: "he made a statement announcement gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/he-made-a-statement-rgull1t-UJsnEtxDIvCSmXxSyP",
            src: "https://media.giphy.com/media/UJsnEtxDIvCSmXxSyP/giphy.gif",
        },
        {
            title: "he made a statement shakespeare gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/he-made-a-statement-rgull1t-i7gs6jNnBnXdiLxJml/",
            src: "https://media.giphy.com/media/i7gs6jNnBnXdiLxJml/giphy.gif",
        },
        {
            title: "he made a statement dog left gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/he-made-a-statement-so-trash-even-the-dog-left-YemOrYHGbs9HTBPKen",
            src: "https://media.giphy.com/media/YemOrYHGbs9HTBPKen/giphy.gif",
        },
        {
            title: "he made a statement so trash gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/rgull1t-he-made-statement-b7JiUst6FOlGY8l0zA",
            src: "https://media.giphy.com/media/b7JiUst6FOlGY8l0zA/giphy.gif",
        },
        {
            title: "he made a statement facts gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/benjammins-statement-made-a-kfbrnDK2uRE2gMWPrm",
            src: "https://media.giphy.com/media/kfbrnDK2uRE2gMWPrm/giphy.gif",
        },
        {
            title: "he made a statement kelp krew gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/kelp-krew-he-made-a-statement-20IpWK1jXiS96ixZpz",
            src: "https://media.giphy.com/media/20IpWK1jXiS96ixZpz/giphy.gif",
        },
        {
            title: "peter, that's not a meme gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/isthisrarelol-dbdbdbzn-thats-just-X6jDx3a0uwnqTffE3d",
            src: "https://media.giphy.com/media/X6jDx3a0uwnqTffE3d/giphy.gif",
        },
        {
            title: "peter, that's not brian gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/thats-not-a-meme-peter-btian-griffan-Wq4wm7JVNO1VZ9DGoL/",
            src: "https://media.giphy.com/media/Wq4wm7JVNO1VZ9DGoL/giphy.gif",
        },
        {
            title: "peter, that's not just a meme gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/thats-not-a-meme-peter-just-vYZih0z5C3wvsdks2X",
            src: "https://media.giphy.com/media/vYZih0z5C3wvsdks2X/giphy.gif",
        },
        {
            title: "jarvis, more alcohol gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/iron-man-graggletwo-tony-stark-more-alcohol-kBwfBzLik1veX0ElHm",
            src: "https://media.giphy.com/media/kBwfBzLik1veX0ElHm/giphy.gif",
        },
        {
            title: "jarvis, more sadness gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/cmaasv6S8tJUafi0Ej",
            src: "https://media.giphy.com/media/cmaasv6S8tJUafi0Ej/giphy.gif",
        },
        {
            title: "jarvis, activate armor protocol gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/meme-iron-man-jarvis-ZDJtqun5EJ36Eq912O/",
            src: "https://media.giphy.com/media/ZDJtqun5EJ36Eq912O/giphy.gif",
        },
        {
            title: "jarvis, activate cortisol mode gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/tony-stark-jarvis-cortisol-NR7mbKbnhnwAQ4Tsjq",
            src: "https://media.giphy.com/media/NR7mbKbnhnwAQ4Tsjq/giphy.gif",
        },
        {
            title: "jarvis, more smirk gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/meme-jarvis-F7MTsSTtFx17fQHlrN",
            src: "https://media.giphy.com/media/F7MTsSTtFx17fQHlrN/giphy.gif",
        },
        {
            title: "jarvis, activate tony stark gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/tony-stark-jarvis-1IZjgpXhHHIw8Lh9Nm/",
            src: "https://media.giphy.com/media/1IZjgpXhHHIw8Lh9Nm/giphy.gif",
        },
        {
            title: "jarvis, activate visor gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/jarvis-karbit-my-bini-kpxtp1PBP6C6nVeSlO/",
            src: "https://media.giphy.com/media/kpxtp1PBP6C6nVeSlO/giphy.gif",
        },
        {
            title: "phonk tuff troll face gif",
            service: "GIPHY",
            href: "https://media.giphy.com/media/ZBWUWwvzm447UhaYup/giphy.gif",
            src: "https://media.giphy.com/media/ZBWUWwvzm447UhaYup/giphy.gif",
        },
        {
            title: "phonk sigma troll face gif",
            service: "GIPHY",
            href: "https://media.giphy.com/media/NHcaTy8eo88NcagDI6/giphy.gif",
            src: "https://media.giphy.com/media/NHcaTy8eo88NcagDI6/giphy.gif",
        },
        {
            title: "phonk phone apple gif",
            service: "GIPHY",
            href: "https://media.giphy.com/media/aWMJvA76tNnBR9gkpT/giphy.gif",
            src: "https://media.giphy.com/media/aWMJvA76tNnBR9gkpT/giphy.gif",
        },
        {
            title: "phonk muppet disbelief gif",
            service: "GIPHY",
            href: "https://media.giphy.com/media/xdLH51eNWZAHrwy5mf/giphy.gif",
            src: "https://media.giphy.com/media/xdLH51eNWZAHrwy5mf/giphy.gif",
        },
        {
            title: "tuff cite gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/cite-tuff-i2Wmqn31cMaSdpLQE1",
            src: "https://media.giphy.com/media/i2Wmqn31cMaSdpLQE1/giphy.gif",
        },
        {
            title: "tuff brainrot gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/meme-brainrot-clearbox88-ia0sMsvTBUQYb59SjK",
            src: "https://media.giphy.com/media/ia0sMsvTBUQYb59SjK/giphy.gif",
        },
        {
            title: "tuff twin gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/tuff-twin-ts-to-jCDmK8hFQpPeXBumtg",
            src: "https://media.giphy.com/media/jCDmK8hFQpPeXBumtg/giphy.gif",
        },
        {
            title: "tuff eman gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/tuff-eman-UXmbkzaUWSUweGcKPh",
            src: "https://media.giphy.com/media/UXmbkzaUWSUweGcKPh/giphy.gif",
        },
        {
            title: "retep family guy gif",
            service: "GIPHY",
            href: "https://giphy.com/gifs/family-guy-peter-griffin-retep-E9tiIVanKGOUd7TSnS/",
            src: "https://media.giphy.com/media/E9tiIVanKGOUd7TSnS/giphy.gif",
        },
        {
            title: "freaky bee freak gif",
            service: "GIPHY",
            href: "https://media.giphy.com/media/xcjE6k4xFEsHUqVbci/giphy.gif",
            src: "https://media.giphy.com/media/xcjE6k4xFEsHUqVbci/giphy.gif",
        },
        {
            title: "freaky cat wtf gif",
            service: "GIPHY",
            href: "https://media.giphy.com/media/8R13hY2pPvuSMGXzOv/giphy.gif",
            src: "https://media.giphy.com/media/8R13hY2pPvuSMGXzOv/giphy.gif",
        },
    ],
};
